import React from 'react';
import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import HeroSection from '../components/Home/HeroSection'
import Service from '../components/Home/Service'
import Blog from '../components/Home/Blog'
import About from '../components/Home/About'
import Testimonials from '../components/Home/Testimonials'
import Pricing from '../components/Home/Pricing'
import Subscribe from '../components/Home/Subscribe'


const inter = Inter({ subsets: ['latin'] })

const index = ({data}) => {
  return (
    <>
      <Head>
        <title>Digital Service Lab</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <HeroSection></HeroSection>
        <Service></Service>
        <Blog data={data}></Blog>
        <About></About>
        <Testimonials></Testimonials>
        <Pricing></Pricing>
        <Subscribe></Subscribe>
        
      </main>
    </>
  );
};

export async function getStaticProps (ctx) {
 const res = await fetch('https://jsonplaceholder.typicode.com/posts')
 const data = await res.json();
  return{
    props:{
      data:data
    }
  }
}


export default index;
