import React from 'react';
import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import HeroSection from '../components/HeroSection';
import Service from '../components/Service';

const inter = Inter({ subsets: ['latin'] })

const index = () => {
  return (
    <>
      <Head>
        <title>Digital Service Lab</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="icon" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />
      </Head>
      <main className={styles.main}>
        <HeroSection></HeroSection>
        <Service></Service>
      </main>
    </>
  );
};

export default index;
